<h1>Modification d\'une annonce</h1>
<form method="post" action="do-post-update.php">
    <fieldset>
        <legend>Annonce</legend>
        <table>
            <td align="right">
                <label for="titreannonce">Titre de l\'annoce :</label>
            </td>
            <td>
                <input type="text" name="titreannonce" id="titreannonce"/><br/>
            </td>
        </table>
        <tr>
            <td align="right">
                <label for="Description">Description du scp :</label>
            </td>
            <td>
                <input type="text" name="Description" id="Description"/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="Photo">Photo</label>
            </td>
            <td>
                <input type="hidden" name="MAX_FILE_SIZE" value="250000"/>
                <input type="file" name="fic" size=50/>
                <input type="submit" value="Envoyer"/>
</form>
</td>
</tr>

</table>
</fieldset>

<p><input type="submit" value="Modifier"/></p></form>';
<?php echo $message; ?>

}
