<h1>Modification d'une annonce</h1>
<form method="post" action="do-post-update.php" enctype="multipart/form-data">
    <fieldset>
        <legend>Annonce</legend>
        <input type="hidden" name="id" value="<?php echo $post->getID() ?>" id="id"/>
        <table>
            <td align="right">
                <label for="titreannonce">Titre de l'annonce :</label>
            </td>
            <td>
                <input type="text" name="titreannonce" value="<?php echo $post->getTitle() ?>" id="titreannonce"/><br/>
            </td>
        </table>
        <table>
            <tr>
                <td align="right">
                    <label for="description">Description :</label>
                </td>
                <td>
                    <input type="text" name="description" value="<?php echo $post->getContent() ?>" id="description"/>
                </td>
            </tr>
            <tr>
                <td align="right">
                    <label for="photo">Photo</label>
                </td>
                <td>
                    <input type="hidden" name="MAX_FILE_SIZE" value="250000"/>
                    <input type="file" name="fileToUpload" size=50/>

                </td>
            </tr>
            </tr>
        </table>
        <input type="submit" name="submit" value="Modifier"/>
    </fieldset>
</form>


<?php echo $message; ?>

