<h1>Insertion d'une annonce</h1>
<form method="post" action="do-post-insert.php" enctype="multipart/form-data">
    <fieldset>
        <legend>Annonce</legend>
        <table>
            <td align="right">
                <label for="titreannonce">Titre de l'annonce :</label>
            </td>
            <td>
                <input type="text" name="titreannonce" id="titreannonce"/><br/>
            </td>
        </table>
        <table>
            <tr>
                <td align="right">
                    <label for="description">Description :</label>
                </td>
                <td>
                    <input type="text" name="description" id="description"/>
                </td>
            </tr>
            <tr>
                <td align="right">
                    <label for="photo">Photo</label>
                </td>
                <td>
                    <input type="hidden" name="MAX_FILE_SIZE" value="250000"/>
                    <input type="file" name="fileToUpload" size=50/>
                    <!--<input type="submit" value="Envoyer"/>-->
                </td>
            </tr>
        </table>
        <p><input type="submit" name="submit" value="Soumettre"/></p>
    </fieldset>
</form>




<?php echo $message; ?>
