<form action="do-sign-up.php" method="post">
    <div>
        Nom d'utilisateur :<br>
        <input type="text" name="username" value="" size="30" placeholder="" required>
    </div>
    <div>
        <br>
    </div>
    <div>
        Mot de passe :<br>
        <input type="password" name="password" value="" size="30" placeholder="" required>
    </div>
    <div>
        Répéter le mot de passe :<br>
        <input type="password" name="passwordx" value="" size="30" placeholder="" required>
    </div>
    <div>
        <br>
    </div>
    <div>
        Prénom :<br>
        <input type="text" name="firstname" value="" size="30" placeholder="" required>
    </div>
    <div>
        <br>
    </div>
    <div>
        Nom de famille :<br>
        <input type="text" name="lastname" value="" size="30" placeholder="" required>
    </div>
    <div>
        <br>
    </div>
    <div>
        E-mail :<br>
        <input type="text" name="email" value="" size="30" placeholder="" required>
    </div>
    <div>
        <br>
    </div>
    <input type="submit" name="submit" value="Créer">
</form>