<form action="do-sign-in.php" method="post">
    <div>
        Nom d'utilisateur :<br>
        <input type="text" name="username" value="" size="30" placeholder="" required>
    </div>
    <div>
        <br>
    </div>
    <div>
        Mot de passe :<br>
        <input type="password" name="password" value="" size="30" placeholder="" required>
    </div>
    <div>
        <br>
    </div>
    <input type="submit" name="submit" value="Connexion">
</form>
<p><a href="sign-up.php">Créer un compte</a></p>
