<form action="user-account-update.php" method="post">
    <div>
        Nom d'utilisateur :<br>
        <input type="text" name="username" value="<?php echo $user->getUsername() ?>" size="30" placeholder="" required>
    </div>
    <div>
        <br>
    </div>
    <div>
        Mot de passe :<br>
        <input type="password" name="password" value="" size="30" placeholder="" required>
    </div>
    <div>
        <br>
    </div>
    <div>
        Prénom :<br>
        <input type="text" name="firstname" value="<?php echo $user->getFirstname() ?>" size="30" placeholder=""
               required>
    </div>
    <div>
        <br>
    </div>
    <div>
        Nom de famille :<br>
        <input type="text" name="lastname" value="<?php echo $user->getLastname() ?>" size="30" placeholder="" required>
    </div>
    <div>
        <br>
    </div>
    <div>
        E-mail :<br>
        <input type="text" name="email" value="<?php echo $user->getEmail() ?>" size="30" placeholder="" required>
    </div>
    <div>
        <br>
    </div>
    <input type="submit" name="submit" value="Modifier">
</form>