<div>
    <a href="list.php"><< Retour</a>
</div>
<h3><?= $post->getTitle() ?></h3>
<p><?= $post->getUsername() ?> - <?= $post->getDateTime() ?></p>
<p><img src="<?= $post->getPhoto() ?>"></p>
<p><?= $post->getContent() ?></p>
<hr>
<?php if (isOwner($post)) { ?>
    [<a href="post-update.php?id=<?= $post->getID() ?>">Modifier</a>]
    [<a href="post-delete.php?id=<?= $post->getID() ?>">Supprimer</a>]
<?php } ?>
