<div>
    <a href="list.php"><< Retour</a>
</div>
<h3><?= $post->getTitle() ?></h3>
<p><?= $post->getUsername() ?> - <?= $post->getDateTime() ?></p>
<p><?= $post->getContent() ?></p>
<hr>
<? if (isOwner($post)) { ?>
    [<a href="post-update.php?id="<?= $post->getID() ?>>Modifier</a>]
    [<a href="post-delete.php?id="<?= $post->getID() ?>>Supprimer</a>]
<? } ?>

<p><a href="user-account-update.php">Modifier mon compte</a></p>